run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - unused
    - misspell
    - revive
    - errorlint
    - bodyclose
    - gofmt
    - goimports

linters-settings:
  errorlint:
    errorf: true
    asserts: true
    comparison: true
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/lith-project/lith
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: increment-decrement
      - name: indent-error-flow
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unreachable-code
      - name: var-declaration
      - name: var-naming
